### ISSUE TITLE
Build error: " `this` has been rewritten to `undefined` "

### ISSUE THREAD

**Issue by dmitry-kurmanov** [sveltejs/component-template#17]
Hello! I've cloned the repo, run `npm i` and then saw the error:

"`this` has been rewritten to `undefined`"

accrording to the "Rollup" doc https://rollupjs.org/guide/en/#error-this-is-undefined we can use the `options.context` and `options.moduleContext`.

Should we set those options ?

**Comment by dmitry-kurmanov** [comment]
for example @YogliB's tempalte [repo ](https://github.com/YogliB/svelte-component-template)`dev` script doesn't show the error

**Comment by antony** [comment]
closing due to age. If this error still occurs, please provide a reproduction and we can look into it.
