### ISSUE TITLE
some documentation suggestions

### ISSUE THREAD

**Issue by mvolkmann** [sveltejs/component-template#21]
Should the documentation include these instructions?

Replace the content of `src/index.js` with a line like the following for each component:

```js
export {default as MyComponentName} from './MyComponentName.svelte';
```

Edit `package.json`.
- Change the `name` property value to `"library-name"`.
- Add a `version` property such as `"version": "0.1.0",`.

**Comment by antony** [comment]
none of these are actually necessary to get this running, so I'd be against adding them to the readme, as they cloud the simplicity of this project.

if people are using this to build real things, you can be sure that they'll adjust these things as need-be.
