### ISSUE TITLE
Storybook implementation

### ISSUE THREAD

**Issue by soullivaneuh** [sveltejs/component-template#23]
As the main goal of this template is tool publish independent components, it would be a great addition to ship a ready-to-use storybook implementation on it.

Ref: https://storybook.js.org/

It may be optional on setup with a command or an indication on the documentation to properly remove it.

**Comment by soullivaneuh** [comment]
I'm following this guide: https://www.learnstorybook.com/intro-to-storybook/svelte/en/get-started/

Quite great to start, but you have some installation and configuration to do.

Having this shipped out of the box would be a great addition IMO.

**Comment by antony** [comment]
@soullivaneuh Whilst storybook is great, it's too much complexity for this simple component template. The Storybook docs demonstrate how to set it up for those who want it.

There is also a project called Svench which aims to be a much more lightweight alternative to Storybook, and I can see this being another good option when it becomes stable.

**Comment by kevmodrome** [comment]
There's even a nice component template starter: https://github.com/rixo/svench-component-template
