### ISSUE TITLE
Document how to use a component outside of svelte

### ISSUE THREAD

**Issue by soullivaneuh** [sveltejs/component-template#24]
I'm not sure this is the good place, but as the documentation says we can use svelte component directly as JS, I think it would be useful to have some sample with at least vanillaJS and maybe some popular framework integration (jQuery, Vue, Angular, React...).

**Comment by Conduitry** [comment]
Maybe just a link to <https://svelte.dev/docs#Client-side_component_API>? I'm not sure this is the right place to be getting into the specifics of various frameworks.

**Comment by antony** [comment]
agreed. this project serves as an example of a very simple rollup configuration to build a pure Javascript function which hydrates into a component. How you use it in other projects depends on the module/import system used there, and documenting it only increases the complexity here.
