### ISSUE TITLE
Local dev server for building and testing components

### ISSUE THREAD

**Issue by rajasegar** [sveltejs/component-template#3]
It would be great if we had tools and scripts for building and testing components within the component template itself so that it will be easy to author new components in Svelte.

**Comment by antony** [comment]
@rajasegar in case it's useful - my parcel based seed has this: https://github.com/antony/svelte-seed/

**Comment by YogliB** [comment]
I've made a [template](https://github.com/YogliB/svelte-component-template) based on the app and component template.

It's Svelte 3 based, but other than that it works exactly the same **and** you can preview your app running `npm run dev`, just as you would do in the full-blown app.

**Comment by thojanssens** [comment]
Why doesn't this repository include something to view the component I'm building? (like a small server and hot reloading)
I do not really see the point of this repository without that basic need? Or how do you view your components that you are building?

**Comment by YogliB** [comment]
@Conduitry Can I PR this?

**Comment by antony** [comment]
@YogliB you are welcome to PR this, but bear in mind it is more likely to be accepted if the PR is bare minimum, as the goal of the template is to provide a clean base.

**Comment by YogliB** [comment]
@antony 
My thought is to make this template more like the [app template](https://github.com/sveltejs/template) with the neccessary modifications to make an independant component.

Something like the template I [published](https://github.com/YogliB/svelte-component-template) minus the extra dev tools (eslint, actions, testing etc.).

**Comment by thojanssens** [comment]
@YogliB aren't testing and formatting basic needs for development?

- You want to view your component in the browser while developing (local server)
- You want to test your component
- You want to enforce proper formatting

This seems the bare minimum to me for developing a component. And these are just dev dependencies, so no impact on the production build of the app depending on the component.

**Comment by antony** [comment]
@thojanssens testing and linting are essential for development but we don't want to endorse or coerce people into using a testing tool or formatting style that might not be right for them.

**Comment by YogliB** [comment]
@antony how about a minimal linting config with only the svelte eslint rules?

**Comment by sonicoder86** [comment]
@antony by not choosing one, for newcomers it feels like viewing, testing and linting a component before publishing is not so important.

**Comment by antony** [comment]
I don't think it's our job to educate people on software quality. It's out of scope for this project.

If somebody believes that linting, testing, and such is important, then they will already have a set of tools that they like, and use those.

Conversely, if they don't believe these things are important, sticking a bunch of tools which might not even be suitable into a template is not going to make them suddenly a better engineer with a focus on quality and testing.

**Comment by antony** [comment]
Closing as we now have SvelteKit for a fuller experience.
