### ISSUE TITLE
Why does it need to be a template only project, why not a full CLI?

### ISSUE THREAD

**Issue by fenilli** [sveltejs/component-template#37]
I was going to start a new component using svelte for a nice change of scenery, but after trying to set up, eslint + typescript + tailwind and so on, its just not worth it, time is money as many people say.

I understand that the template is more like to be a bare minimum to run svelte and so any developer can use any tool they want, but we all know that the bare minimum is never a thing.

Why not follow the vue way in this one, making a cli where you just need to click if you want or not some features, makes it easier for people to start using svelte without looking for 100 websites to find out that none of those actually work or are easy to set up.

**Comment by dummdidumm** [comment]
We are working an setup CLI for [SvelteKit](https://github.com/sveltejs/kit) which will become the recommended way to build apps/sites with Svelte. You can run `npm init svelte@next` in an empty project folder to see it in action. There's also the [svelte adders](https://github.com/svelte-add/svelte-adders) community project to add more on top after the setup. Supporting all possible use cases is cumbersome though. Luckily, there are many starter templates out there, one of them could provide you the setup you want.

**Comment by fenilli** [comment]
Thank you I will check SvelteKit out, there is also no need to add all possible use cases, just the most used ones.

**Comment by nileshtrivedi** [comment]
@dummdidumm Sometimes, I don't want to build a new app or site. I just want to generate web components and either add them to an existing non-NPM app (Django, Rails, Phoenix etc) or publish them as standalone JS files to be used by others as libraries. A minimal CLI that takes a .svelte file and produces a .js file would be quite useful, actually.

**Comment by ignatiusmb** [comment]
You can think of `svelte-kit package` as the minimal CLI, we're also planning to add the compiled version of the output, it's tracked in https://github.com/sveltejs/kit/issues/2572, so please chime in there with your use cases.
