### ISSUE TITLE
Upgrade template for v3 of Svelte

### ISSUE THREAD

**Issue by asif-ahmed-1990** [sveltejs/component-template#4]
It would be great if this template is updated for v3. Also a custom element example would be awesome!

**Comment by sisou** [comment]
For v3 compatibility, check the PR I just opened: https://github.com/sveltejs/component-template/pull/5.

To export a custom element, add
```
svelte({
  customElement: true,
  tag: 'my-tag-name'
}),
```
to the `rollup.config.js` plugins section. (You can also add `<svelte:options tag="my-tag-name">` to the component file.)

**Comment by asif-ahmed-1990** [comment]
@sisou Thanks. Will try it out

**Comment by dmitry-kurmanov** [comment]
@asifahmedfw @sisou the PR above doesn't compile with the:

```js
 "svelte": "^3.2.1"
```

I've got an error: 

```js
[!] (svelte plugin) Error: Unrecognized option 'onwarn'
src\index.html
Error: Unrecognized option 'onwarn'
    at Object.keys.forEach.key (c:\Users\kurmanov.dmitry\Desktop\my-new-component\node_modules\svelte\compiler.js:23690:20)
```

**Comment by sisou** [comment]
Coming from a fresh copy, I do not get that error. Do you use any special code? Also, the extension for Svelte v3 is `.svelte`. Have you tried that?

**Comment by dmitry-kurmanov** [comment]
@sisou you are right. It was a mistake on my side. It correctly compiles.

**Comment by YogliB** [comment]
I've made a [template](https://github.com/YogliB/svelte-component-template) based on the app and component template.

It's Svelte 3 based, but other than that it works exactly the same **and** you can preview your app running `npm run dev`, just as you would do in the full-blown app.

**Comment by pngwn** [comment]
The template is now updated for v3.
