### ISSUE TITLE
Custom Element build target is missing

### ISSUE THREAD

**Issue by nileshtrivedi** [sveltejs/component-template#40]
If the Svelte component includes `<svelte:options tag="my-element" />`, then the following warning is shown with `npm run build`:

```
(!) Plugin svelte: The 'tag' option is used when generating a custom element. Did you forget the 'customElement: true' compile option?
src/Component.svelte
1: <svelte:options tag="my-element" />
```

Changing the svelte plugin call in `rollup.config.js` (following the example in [their own README](https://github.com/sveltejs/rollup-plugin-svelte)) to this:

```
svelte({
	compilerOptions: {customElement: true}
}),
```

throws this error message: 

```
% npm run build

> build
> rollup -c


src/index.js → dist/index.mjs, dist/index.js...
[!] (plugin svelte) Error: Unrecognized option 'compilerOptions'
src/Component.svelte
Error: Unrecognized option 'compilerOptions'
    at /Users/nileshtr/my-new-component/node_modules/svelte/compiler.js:31305:20
```

It's not clear what change is needed in `rollup.config.js` to get a custom element build by setting `customElement: true` compile option. Ideally, this template should be ready to export the components as custom elements. But at minimum, the README should document what change to make in the config to get a custom element build.

**Comment by antony** [comment]
Looks like the readme references `rollup-plugin-svelte@7` but `package.json` references `rollup-plugin-svelte@6`

**Comment by antony** [comment]
Fixed by https://github.com/sveltejs/component-template/pull/36
